on: 
  push:
    tags:
    - '*'
    
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build Debug APK
      run: ./gradlew --no-daemon assembleDebug
  
    - uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "app/build/outputs/apk/debug/app-debug.apk"
        body: "Debug APK"
        token: ${{ secrets.GITHUB_TOKEN }}
